-- 	Procedimento que atualiza Estado na Tabela <PlanoDeEnsino>
-- 	Remove tuplas de <Revisao> que têm ligação com o Plano de Ensino ao qual deseja-se atualizar informações
-- e atualiza informações na tabela. 

CREATE OR REPLACE PROCEDURE AlteraEstadoPlanoEnsino
(IN NOME_PROFESSOR VARCHAR(30), IN NOVO_ESTADO VARCHAR(9), IN NOME_DISCIPLINA VARCHAR(30),
IN LETRA CHAR, IN ANO CHAR(4), IN SEMESTRE CHAR(4), IN PARECER CHAR(20))
LANGUAGE SQL
BEGIN
	DECLARE SIAPE_P VARCHAR(6);
	DECLARE ID_TURMA INTEGER;
	DECLARE DATA_ATUAL DATE;
	DECLARE DATA_ANTERIOR DATE;
	DECLARE ESTADO_ANTERIOR VARCHAR(9);
	
	SET DATA_ATUAL = CURRENT DATE;
	
	-- RECUPERA SIAPE
	SELECT S.SIAPE INTO SIAPE_P FROM SERVIDOR AS S, PESSOA AS P
	WHERE P.NOME = NOME_PROFESSOR AND P.CPF = S.CPF;
	
	-- RECUPERA IDTURMA
	SELECT T.IDTURMA INTO ID_TURMA FROM TURMA AS T, DISCIPLINA AS D
	WHERE T.LETRA = LETRA AND T.ANO = ANO AND T.SEMESTRE = SEMESTRE
	AND D.NOME = NOME_DISCIPLINA AND D.CODIGODISCIPLINA = T.CODDISCIPLINA;
	
	-- RECUPERA ESTADO ANTERIOR DO PLANO DE ENSINO
	SELECT MAX(R.DATADEREVISAO) INTO DATA_ANTERIOR FROM REVISAO AS R
	WHERE R.SIAPE = SIAPE_P AND R.IDTURMA = ID_TURMA;
	
	SELECT PE_ESTADO INTO ESTADO_ANTERIOR FROM REVISAO AS R
	WHERE R.DATADEREVISAO = DATA_ANTERIOR AND R.IDTURMA = ID_TURMA;
	
	DELETE FROM REVISAO AS R WHERE R.SIAPE = SIAPE_P AND R.IDTURMA = ID_TURMA AND R.PE_ESTADO = ESTADO_ANTERIOR;
	DELETE FROM PLANODEENSINO AS PE WHERE PE.SIAPE = SIAPE_P AND PE.IDTURMA = ID_TURMA AND PE.ESTADO = ESTADO_ANTERIOR;
	INSERT INTO PLANODEENSINO VALUES (SIAPE_P, NOVO_ESTADO, ID_TURMA);
	INSERT INTO REVISAO VALUES (SIAPE_P, NOVO_ESTADO, ID_TURMA, PARECER, ESTADO_ANTERIOR, DATA_ATUAL);
	
END}