--SELECT * FROM membro
--SELECT * FROM PESSOA
--SELECT * FROM vDisciplinasEmOferta OK
SELECT * FROM vdocentecargoadministrativo OK
--SELECT * FROM VCONTATOSSERVIDOR ok
--SELECT * FROM VPLANODEENSINO ok