CREATE OR REPLACE TRIGGER INSERIR_NOVA_PAUTA
INSTEAD OF INSERT ON REUNIAO_COM_PAUTAS
REFERENCING NEW AS NEW_VAL
FOR EACH ROW
INSERT INTO ITEM_DE_PAUTA
VALUES(NEW_VAL.numero_pauta, NEW_VAL.numero_reuniao, NEW_VAL.descricao, NEW_VAL.data_item_de_pauta, NEW_VAL.status_pauta, NEW_VAL.documentos)