CREATE OR REPLACE TRIGGER T_PROPOE_DATA_INVALIDA_INSERT
    BEFORE INSERT ON PROPOE
    REFERENCING NEW AS NEW_PROPOE
    FOR EACH ROW MODE DB2SQL
        WHEN (NEW_PROPOE.DATA_APROVACAO > current date)
            SIGNAL SQLSTATE '75010' ('Data informada é maior que a data atual')