-- 	Procedimento que atualiza Estado na Tabela <PlanoDeEnsino>
-- 	Remove tuplas de <Revisao> que têm ligação com o Plano de Ensino ao qual deseja-se atualizar informações
-- e atualiza informações na tabela. 

CREATE OR REPLACE PROCEDURE AdicionaMembroConselho
(IN VAL_SIAPE VARCHAR(6),IN VAL_CONSELHO INT,IN VAL_PORTARIA VARCHAR(20))
LANGUAGE SQL
BEGIN
	DECLARE CPF_ATUAL VARCHAR(11);
	DECLARE SIAPEAUX INT DEFAULT 0;
	DECLARE TIPO_MEMBRO VARCHAR(20);
		
	-- RECUPERA CPF
	SELECT CPF INTO CPF_ATUAL FROM SERVIDOR AS S
	WHERE S.SIAPE = VAL_SIAPE;
	
	-- VERIFICA TA OU DOCENTE
	SELECT COUNT(SIAPE) INTO SIAPEAUX FROM TAS WHERE TAS.SIAPE = VAL_SIAPE;
	
	IF SIAPEAUX = 0 THEN SET TIPO_MEMBRO = 'DOCENTE'; 
	ELSE
	SET TIPO_MEMBRO = 'TA';
	END IF;
		
	INSERT INTO MEMBRO VALUES (DEFAULT,CPF_ATUAL,VAL_CONSELHO, VAL_PORTARIA, TIPO_MEMBRO, NULL);
END}

-- Testa o procedure
--call AdicionaMembroConselho('Pompeu Pomposo', '14', '14');
