-- 	Procedimento que remove um conselho do banco
CREATE OR REPLACE PROCEDURE RemoverConselho
(IN VAL_CONSELHO INT)
LANGUAGE SQL
BEGIN
	DECLARE TIPO_CONSELHO VARCHAR(12);
	
	SELECT TIPO INTO TIPO_CONSELHO FROM CONSELHO AS C WHERE C.CODIGOCONSELHO = VAL_CONSELHO ;
	-- VERIFICA O TIPO DO CONSELHO
	IF TIPO_CONSELHO = 'DEPARTAMENTO' THEN 	DELETE FROM CONSELHODEDEPARTAMENTO AS CD WHERE CD.CODIGOCONSELHO = VAL_CONSELHO;
	END IF;
	
	-- DELETA MEMBROS DO CONSELHO
	DELETE FROM MEMBRO AS M WHERE M.CODIGO_CONSELHO = VAL_CONSELHO;
	-- DELETA CONSELHO
	DELETE FROM CONSELHO AS C WHERE C.CODIGOCONSELHO = VAL_CONSELHO;
END}

-- Testa o procedure
--call RemoverConselho(10);
