DROP TABLE SERVIDOR;
DROP TABLE DOCENTE;
DROP TABLE TAS;
DROP TABLE DOCENTE_CARGO_ADMINISTRATIVO;

DROP TABLE PESSOA;

CREATE TABLE PESSOA(
	CPF CHAR(11) NOT NULL,
	PRIMARY KEY (CPF)
);

CREATE TABLE SERVIDOR(
	CPF CHAR(11) NOT NULL,
	SIAPE CHAR(6) NOT NULL,
	PRIMARY KEY (SIAPE),
	FOREIGN KEY (CPF) REFERENCES PESSOA(CPF)
);

CREATE TABLE TAS(
	SIAPE CHAR(6) NOT NULL,
	FOREIGN KEY (SIAPE) REFERENCES SERVIDOR(SIAPE),
	PRIMARY KEY (SIAPE)
);

CREATE TABLE DOCENTE(
	SIAPE CHAR(6) NOT NULL,
	POSICAO VARCHAR(30) NOT NULL,
	TIPO_DOCENTE VARCHAR(30) NOT NULL,
	TOTAL_CARGA_SEMESTRE INT,
	TIPO_LICENCA VARCHAR(20),
	PRAZO_LICENCA INT,
	RAZAO_ALIVIO VARCHAR(40),
	CARGA_HORARIA_ALIVIO INT,
	FOREIGN KEY (SIAPE) REFERENCES SERVIDOR(SIAPE),
	PRIMARY KEY (SIAPE)
);
CREATE TABLE DOCENTE_CARGO_ADMINISTRATIVO(
	SIAPE CHAR(6) NOT NULL,
	PERIODO_INICIO DATE NOT NULL,
	PERIODO_TERMINO DATE,
	NOME_CARGO VARCHAR(30) NOT NULL,
	FOREIGN KEY (SIAPE) REFERENCES DOCENTE(SIAPE),
	PRIMARY KEY (SIAPE, PERIODO_INICIO, NOME_CARGO)
);