INSERT INTO CONSELHO(CODIGOCONSELHO,TIPO)
VALUES('CDE41AF12',1);
INSERT INTO CONSELHO(CODIGOCONSELHO,TIPO)
VALUES('CDE3FKAS12',0);
INSERT INTO CONSELHO(CODIGOCONSELHO,TIPO)
VALUES('CDE4BCDAQ',1);
INSERT INTO CONSELHO(CODIGOCONSELHO,TIPO)
VALUES('A3E6FKAS12',0);
INSERT INTO CONSELHO(CODIGOCONSELHO,TIPO)
VALUES('3ABA01L69F',1);
INSERT INTO CONSELHO(CODIGOCONSELHO,TIPO)
VALUES('APEO254MLA',1);
INSERT INTO CONSELHO(CODIGOCONSELHO,TIPO)
VALUES('LKMN548T94',1);

INSERT INTO CONSELHODEDEPARTAMENTO(CODIGOCONSELHO,SIGLA)
VALUES('CDE41AF12','DC');
INSERT INTO CONSELHODEDEPARTAMENTO(CODIGOCONSELHO,SIGLA)
VALUES('CDE4BCDAQ','DM');
INSERT INTO CONSELHODEDEPARTAMENTO(CODIGOCONSELHO,SIGLA)
VALUES('3ABA01L69F','DF');
INSERT INTO CONSELHODEDEPARTAMENTO(CODIGOCONSELHO,SIGLA)
VALUES('APEO254MLA','DQ');
INSERT INTO CONSELHODEDEPARTAMENTO(CODIGOCONSELHO,SIGLA)
VALUES('LKMN548T94','DM');
